### ISSUE TITLE
Add readlinkat to list of allowed syscalls

### ISSUE THREAD

**Issue by marximimus** [varqox/simlib#2]
Programy skompilowany z gcc i clangiem zanim wywołają funkcję main, używają syscalla readlink, który jest dopuszczony przez sandbox simliba. Niestety na niektórych dystrybucjach systemu operacyjnego GNU+Linux (w tym na archu) zamiast syscalla readlink używany jest syscall readlinkat, więc każdy  program dostaje werdykt forbidden syscall (np. przy przygotowywaniu paczek używając sipa). Czy istniałaby możliwość, aby dodać ten syscall do listy dopuszczonych syscallów lub rozwiązać ten problem w inny sposób?

**Comment by varqox** [comment]
Sip should be fixed now.
